name: haliburton
favicon: null
layout_spectrum: 0.3801682172343135
typography_spectrum: 0.2544672507792711
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9384506335482001
  lightness: 0.25219356664456427
  saturation: 0.09976621111854911
  rhythmicContrast: 0.7775731750298291
purpose: []
